version: '2'
services:

  conjur_master:
    image: conjur-appliance:5-latest
    container_name: conjur_master
    build: ./build/conjur_master
    ports:
      - 443:443
    security_opt:
      - seccomp:unconfined
    restart: always

  cli:
    container_name: conjur_cli
    hostname: conjur_cli
    image: cyberark/conjur-cli:5-latest
    volumes:
      - .:/demo_root:z
    entrypoint: sleep
    command: infinity
    restart: always

  client:
    image: client_node:latest
    container_name: client_node
    build: ./build/client_node
    volumes:
      - ./demo:/demo
    entrypoint: sleep
    command: infinity
    restart: always

  concourse-db:
    image: postgres
    container_name: concourse-db
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse
    container_name: concourse
    entrypoint: concourse
    command: quickstart --add-local-user cuser:cpass --main-team-local-user cuser --external-url http://localhost:8080 --worker-work-dir /opt/concourse/worker
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    restart: always

